# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args:
          - --fix
        exclude: ^examples/.*\.py$ # Exclude example scripts due to IPython magic
      - id: ruff-format
        exclude: ^examples/.*\.py$ # Exclude example scripts due to IPython magic

  - repo: local
    hooks:
      - id: generate-client
        name: Generate API Client
        entry: scripts/generate-client.sh
        language: script
        files: backend/app/api/
        types: [python]
      - id: generate-enums
        name: Generate Enums
        entry: scripts/generate-enums.sh
        language: script
        files: shared/taxonomies\.json

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
