# Copyright 2024 Rostlab.
# SPDX-License-Identifier: Apache-2.0

site_name: FlatProt
nav:
  - Home: index.md
  - CLI: cli.md
  - File Formats:
      - Matrix Files: file_formats/matrix.md
      - Style Files: file_formats/style.md
      - Annotation Files: file_formats/annotations.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - json
    - toml
    - bash
    - numpy
site_url: https://t03i.github.io/FlatProt/
repo_url: https://github.com/t03i/FlatProt
markdown_extensions:
  - admonition
