# FlatProt Annotation Example
# This file demonstrates the different types of annotations available in FlatProt

[[annotations]]
type = "point"
label = "Catalytic Site"
chain = "A"
index = 45

[[annotations]]
type = "point"
label = "Binding Site"
chain = "A"
index = 78

[[annotations]]
type = "line"
label = "Salt Bridge"
chain = "A"
indices = [45, 67]    # Connect residue 45 to 67

[[annotations]]
type = "line"
label = "H-Bond"
chain = "A"
indices = [23, 28]

[[annotations]]
type = "area"
label = "Binding Pocket"
chain = "A"
range = { start = 45, end = 69 }


[[annotations]]
type = "area"
label = "N-terminal Domain"
chain = "A"
range = { start = 1, end = 25 }
