# Style definitions for protein secondary structures

[helix]
fill_color = "#FF7D7D"   # Light red
stroke_color = "#CC0000" # Darker red
stroke_width = 1.5
opacity = 0.8
radius = 1.2             # Radius for helix representation

[sheet]
fill_color = "#7D7DFF"   # Light blue
stroke_color = "#0000CC" # Darker blue
stroke_width = 1.5
opacity = 0.8
arrow_width = 3.0        # Width of beta sheet arrows

[coil]
stroke_color = "#777777" # Gray
stroke_width = 1.0
opacity = 0.7

# Annotation styles

[point_annotation]
radius = 5               # Will be converted to stroke_width = 10
fill_color = "#FFA500"   # Orange
stroke_color = "#000000" # Black
opacity = 0.9
shape = "circle"         # Default shape for point annotations

[line_annotation]
stroke_color = "#00CC00" # Green
stroke_width = 2.0
opacity = 1.0
dash_array = "5,3"       # Creates a dashed line pattern

[area_annotation]
fill_color = "#FFFF00"   # Yellow
stroke_color = "#CCCC00" # Darker yellow
stroke_width = 1.0
opacity = 0.3
border_radius = 5        # Rounded corners for area annotations

# Global canvas settings

[canvas]
background_color = "#FFFFFF" # White background
width = 800
height = 600
padding = 50

# Default annotation styles if not specified in specific annotation types

[annotation]
text_color = "#000000"            # Black text
font_family = "Arial, sans-serif"
font_size = 12
font_weight = "bold"
