name: Documentation

on:
    workflow_dispatch:
        inputs:
            ref:
                description: 'Branch, tag, or SHA to build docs from'
                required: true
                default: 'main'
                type: string

jobs:
    docs:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
        env:
            UV_TOOL_DIR: /tmp/.uv-tools
        permissions:
            pages: write
            id-token: write
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.ref }}
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version-file: "pyproject.toml"
    
            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  enable-cache: true
                  cache-dependency-glob: "uv.lock"

            - name: Build documentation
              run: mkdocs build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./site
