name: Python Build Workflow

on:
    workflow_call:
        inputs:
            tag:
                required: true
                type: string

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        environment:
            name: release
            url: https://pypi.org/p/flatprot
        env:
            UV_TOOL_DIR: /tmp/.uv-tools
        permissions:
            id-token: write
            contents: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ inputs.tag }}

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  enable-cache: true
                  cache-dependency-glob: "uv.lock"

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version-file: "pyproject.toml"

            - name: Build Python Package
              run: uv build
              
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: dist/
                  tag_name: ${{ github.ref_name }}
                  draft: true

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
